parallel-jobs = 1

# Morphe
[YouTube]
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube"
patcher-args = "-e 'Change header' -Ocustom=icons/YouTube/header -e 'Custom branding' -OcustomIcon=icons/YouTube/branding -OcustomName=Morphe"

[Music]
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music"
patcher-args = "-e 'Change header' -Ocustom=icons/Music/header -e 'Custom branding' -OcustomIcon=icons/Music/branding -OcustomName='Morphe Music'"
arch = "both"

[Reddit]
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit"
version = "2026.10.0"
patcher-args = "-e 'Custom branding name for Reddit' -OappName='Morphe Reddit'"

# Piko
[X]
uptodown-dlurl = "https://twitter.en.uptodown.com/android"
# apkmirror-dlurl = "https://apkmirror.com/apk/x-corp/twitter"
patches-source = "crimera/piko"
brand = "Piko"
included-patches = "'Browse tweet object' 'Dynamic color'"

[Twitter]
uptodown-dlurl = "https://twitter.en.uptodown.com/android"
# apkmirror-dlurl = "https://apkmirror.com/apk/x-corp/twitter"
patches-source = "crimera/piko"
brand = "Piko"
included-patches = "'Bring back twitter' 'Browse tweet object' 'Dynamic color'"
